# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/tdimitrov/rpcap
    steps:
      - checkout
      - run:
          name: Install deps
          command: make dep
      - run:
          name: Build
          command: make build
      - run:
          name: Run tests
          command: make test